/*
 * This file was automatically generated by EvoSuite
 * Sun Jun 03 18:07:06 GMT 2018
 */

package ch.ge.ve.commons.crypto.utils;

import org.junit.Test;
import static org.junit.Assert.*;
import ch.ge.ve.commons.crypto.utils.SecureRandomFactory;
import java.security.SecureRandom;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SecureRandomFactory_ESTest extends SecureRandomFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SecureRandom secureRandom0 = SecureRandomFactory.createPRNG();
      assertNotNull(secureRandom0);
  }
}
