/*
 * This file was automatically generated by EvoSuite
 * Sun Jun 03 18:13:55 GMT 2018
 */

package ch.ge.ve.commons.crypto.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import ch.ge.ve.commons.crypto.exceptions.AuthenticationTagMismatchException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AuthenticationTagMismatchException_ESTest extends AuthenticationTagMismatchException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AuthenticationTagMismatchException authenticationTagMismatchException0 = new AuthenticationTagMismatchException("bi4]");
  }
}
