/*
 * This file was automatically generated by EvoSuite
 * Sun Jun 03 18:13:47 GMT 2018
 */

package ch.ge.ve.commons.crypto.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import ch.ge.ve.commons.crypto.exceptions.CryptoOperationRuntimeException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CryptoOperationRuntimeException_ESTest extends CryptoOperationRuntimeException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable("!{V)%r\"y.kmiCtB");
      CryptoOperationRuntimeException cryptoOperationRuntimeException0 = new CryptoOperationRuntimeException("BFn{+']", mockThrowable0, true, true);
      CryptoOperationRuntimeException cryptoOperationRuntimeException1 = new CryptoOperationRuntimeException("BFn{+']", cryptoOperationRuntimeException0);
      assertFalse(cryptoOperationRuntimeException1.equals((Object)cryptoOperationRuntimeException0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      CryptoOperationRuntimeException cryptoOperationRuntimeException0 = new CryptoOperationRuntimeException("!{V)%r\"y.kmiCtB");
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable("!{V)%r\"y.kmiCtB");
      CryptoOperationRuntimeException cryptoOperationRuntimeException0 = new CryptoOperationRuntimeException("BFn{+']", mockThrowable0, true, true);
      CryptoOperationRuntimeException cryptoOperationRuntimeException1 = new CryptoOperationRuntimeException(cryptoOperationRuntimeException0);
      assertFalse(cryptoOperationRuntimeException1.equals((Object)cryptoOperationRuntimeException0));
  }
}
