/*
 * This file was automatically generated by EvoSuite
 * Sun Jun 03 18:13:40 GMT 2018
 */

package ch.ge.ve.commons.crypto.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import ch.ge.ve.commons.crypto.exceptions.CryptoConfigurationRuntimeException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CryptoConfigurationRuntimeException_ESTest extends CryptoConfigurationRuntimeException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CryptoConfigurationRuntimeException cryptoConfigurationRuntimeException0 = new CryptoConfigurationRuntimeException("ch.ge.ve.commons.crypto.exceptions.CryptoConfigurationRuntimeException");
      CryptoConfigurationRuntimeException cryptoConfigurationRuntimeException1 = new CryptoConfigurationRuntimeException("ch.ge.ve.commons.crypto.exceptions.CryptoConfigurationRuntimeException", cryptoConfigurationRuntimeException0);
      assertFalse(cryptoConfigurationRuntimeException1.equals((Object)cryptoConfigurationRuntimeException0));
  }
}
