/*
 * This file was automatically generated by EvoSuite
 * Sun Jun 03 18:13:43 GMT 2018
 */

package ch.ge.ve.commons.crypto.exceptions;

import org.junit.Test;
import static org.junit.Assert.*;
import ch.ge.ve.commons.crypto.exceptions.ProtocolNotRespectedException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ProtocolNotRespectedException_ESTest extends ProtocolNotRespectedException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ProtocolNotRespectedException protocolNotRespectedException0 = new ProtocolNotRespectedException("");
  }
}
