/*
 * This file was automatically generated by EvoSuite
 * Sun Jun 03 17:55:50 GMT 2018
 */

package ch.ge.ve.offlineadmin.util;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ch.ge.ve.offlineadmin.util.PropertyConfigurationServiceFactory;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PropertyConfigurationServiceFactory_ESTest extends PropertyConfigurationServiceFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PropertyConfigurationServiceFactory propertyConfigurationServiceFactory0 = new PropertyConfigurationServiceFactory();
      // Undeclared exception!
      try { 
        propertyConfigurationServiceFactory0.propertyConfigurationService();
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // Could not initialize class ch.ge.ve.commons.properties.PropertyConfigurationService
         //
         verifyException("ch.ge.ve.offlineadmin.util.PropertyConfigurationServiceFactory", e);
      }
  }
}
