/*
 * This file was automatically generated by EvoSuite
 * Sun Jun 03 17:55:57 GMT 2018
 */

package ch.ge.ve.commons.streamutils;

import org.junit.Test;
import static org.junit.Assert.*;
import ch.ge.ve.commons.streamutils.SafeObjectSecurityRuntimeException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class SafeObjectSecurityRuntimeException_ESTest extends SafeObjectSecurityRuntimeException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      SafeObjectSecurityRuntimeException safeObjectSecurityRuntimeException0 = new SafeObjectSecurityRuntimeException("#7?g*(I[A]+N2j@~A3");
  }
}
