/*
 * This file was automatically generated by EvoSuite
 * Sun Jun 03 18:13:33 GMT 2018
 */

package ch.ge.ve.commons.crypto;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ch.ge.ve.commons.crypto.PropertyConfigurationProviderSecurityImpl;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PropertyConfigurationProviderSecurityImpl_ESTest extends PropertyConfigurationProviderSecurityImpl_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PropertyConfigurationProviderSecurityImpl propertyConfigurationProviderSecurityImpl0 = null;
      try {
        propertyConfigurationProviderSecurityImpl0 = new PropertyConfigurationProviderSecurityImpl();
        fail("Expecting exception: RuntimeException");
      
      } catch(RuntimeException e) {
         //
         // Unable to load the configuration file from the classpath: common-crypto.properties
         //
         verifyException("ch.ge.ve.commons.crypto.PropertyConfigurationProviderSecurityImpl", e);
      }
  }
}
