/*
 * This file was automatically generated by EvoSuite
 * Sun Jun 03 17:51:37 GMT 2018
 */

package ch.ge.ve.offlineadmin.controller;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ch.ge.ve.offlineadmin.controller.ConsoleOutputControl;
import ch.ge.ve.offlineadmin.controller.PasswordDialogController;
import java.util.ResourceBundle;
import javafx.beans.property.StringProperty;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PasswordDialogController_ESTest extends PasswordDialogController_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      PasswordDialogController passwordDialogController0 = new PasswordDialogController((ResourceBundle) null, (ConsoleOutputControl) null);
      // Undeclared exception!
      try { 
        passwordDialogController0.promptForPasswords((StringProperty) null, (StringProperty) null, false);
        fail("Expecting exception: NoClassDefFoundError");
      
      } catch(NoClassDefFoundError e) {
         //
         // javafx.scene.layout.Pane
         //
         verifyException("javafx.scene.control.Dialog", e);
      }
  }
}
