/*
 * This file was automatically generated by EvoSuite
 * Sun Jun 03 17:49:21 GMT 2018
 */

package ch.ge.ve.offlineadmin.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import ch.ge.ve.offlineadmin.exception.KeyGenerationRuntimeException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class KeyGenerationRuntimeException_ESTest extends KeyGenerationRuntimeException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      KeyGenerationRuntimeException keyGenerationRuntimeException0 = new KeyGenerationRuntimeException("&O/}[HTEW=9 }-S");
      KeyGenerationRuntimeException keyGenerationRuntimeException1 = new KeyGenerationRuntimeException("", keyGenerationRuntimeException0);
      assertFalse(keyGenerationRuntimeException1.equals((Object)keyGenerationRuntimeException0));
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      KeyGenerationRuntimeException keyGenerationRuntimeException0 = new KeyGenerationRuntimeException("&O/}[HTEW=9 }-S");
      KeyGenerationRuntimeException keyGenerationRuntimeException1 = new KeyGenerationRuntimeException(keyGenerationRuntimeException0);
      assertFalse(keyGenerationRuntimeException1.equals((Object)keyGenerationRuntimeException0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      KeyGenerationRuntimeException keyGenerationRuntimeException0 = new KeyGenerationRuntimeException("&O/}[HTEW=9 }-S");
      KeyGenerationRuntimeException keyGenerationRuntimeException1 = new KeyGenerationRuntimeException("", keyGenerationRuntimeException0, false, false);
      assertFalse(keyGenerationRuntimeException1.equals((Object)keyGenerationRuntimeException0));
  }
}
