/*
 * This file was automatically generated by EvoSuite
 * Sun Jun 03 17:49:13 GMT 2018
 */

package ch.ge.ve.offlineadmin.exception;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ch.ge.ve.offlineadmin.exception.MissingKeyFilesException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.lang.MockThrowable;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class MissingKeyFilesException_ESTest extends MissingKeyFilesException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      MissingKeyFilesException missingKeyFilesException0 = new MissingKeyFilesException("ch.ge.ve.offlineadmin.exception.MissingKeyFilesException");
      MissingKeyFilesException missingKeyFilesException1 = null;
      try {
        missingKeyFilesException1 = new MissingKeyFilesException("ch.ge.ve.offlineadmin.exception.MissingKeyFilesException", missingKeyFilesException0, true, false);
        fail("Expecting exception: ArrayIndexOutOfBoundsException");
      
      } catch(ArrayIndexOutOfBoundsException e) {
         //
         // 0
         //
         verifyException("org.evosuite.runtime.mock.java.lang.MockException", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      MockThrowable mockThrowable0 = new MockThrowable();
      MissingKeyFilesException missingKeyFilesException0 = new MissingKeyFilesException("", mockThrowable0, true, true);
      MissingKeyFilesException missingKeyFilesException1 = new MissingKeyFilesException(missingKeyFilesException0);
      assertFalse(missingKeyFilesException1.equals((Object)missingKeyFilesException0));
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      MissingKeyFilesException missingKeyFilesException0 = new MissingKeyFilesException(".~U?f1=/dW\"'($");
      MockThrowable mockThrowable0 = new MockThrowable("v[<gDdQ*Ds{r", missingKeyFilesException0);
      MissingKeyFilesException missingKeyFilesException1 = new MissingKeyFilesException("9he0ers=HG?)/@R}", mockThrowable0);
      assertFalse(missingKeyFilesException1.equals((Object)missingKeyFilesException0));
  }
}
