/*
 * This file was automatically generated by EvoSuite
 * Sun Jun 03 17:49:06 GMT 2018
 */

package ch.ge.ve.offlineadmin.services;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ch.ge.ve.commons.properties.PropertyConfigurationService;
import ch.ge.ve.offlineadmin.services.BallotCipherServiceFactory;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class BallotCipherServiceFactory_ESTest extends BallotCipherServiceFactory_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      BallotCipherServiceFactory ballotCipherServiceFactory0 = null;
      try {
        ballotCipherServiceFactory0 = new BallotCipherServiceFactory((PropertyConfigurationService) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ch.ge.ve.offlineadmin.services.BallotCipherServiceFactory", e);
      }
  }
}
